/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    locationImageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    description: string;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('locationImageUrl' in value) || value['locationImageUrl'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'date': json['date'],
        'address': json['address'],
        'locationImageUrl': json['locationImageUrl'],
        'description': json['description'],
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'date': value['date'],
        'address': value['address'],
        'locationImageUrl': value['locationImageUrl'],
        'description': value['description'],
    };
}

