/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
} from './Event';

/**
 * 
 * @export
 * @interface Events
 */
export interface Events {
    /**
     * 
     * @type {Array<Event>}
     * @memberof Events
     */
    eventsList: Array<Event>;
}

/**
 * Check if a given object implements the Events interface.
 */
export function instanceOfEvents(value: object): value is Events {
    if (!('eventsList' in value) || value['eventsList'] === undefined) return false;
    return true;
}

export function EventsFromJSON(json: any): Events {
    return EventsFromJSONTyped(json, false);
}

export function EventsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Events {
    if (json == null) {
        return json;
    }
    return {
        
        'eventsList': ((json['eventsList'] as Array<any>).map(EventFromJSON)),
    };
}

export function EventsToJSON(value?: Events | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'eventsList': ((value['eventsList'] as Array<any>).map(EventToJSON)),
    };
}

