/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Hourly
 */
export interface Hourly {
    /**
     * 
     * @type {string}
     * @memberof Hourly
     */
    time: string;
    /**
     * 
     * @type {number}
     * @memberof Hourly
     */
    temp: number;
    /**
     * 
     * @type {number}
     * @memberof Hourly
     */
    humidity: number;
    /**
     * 
     * @type {number}
     * @memberof Hourly
     */
    wind: number;
    /**
     * 
     * @type {number}
     * @memberof Hourly
     */
    precipitation: number;
}

/**
 * Check if a given object implements the Hourly interface.
 */
export function instanceOfHourly(value: object): value is Hourly {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('temp' in value) || value['temp'] === undefined) return false;
    if (!('humidity' in value) || value['humidity'] === undefined) return false;
    if (!('wind' in value) || value['wind'] === undefined) return false;
    if (!('precipitation' in value) || value['precipitation'] === undefined) return false;
    return true;
}

export function HourlyFromJSON(json: any): Hourly {
    return HourlyFromJSONTyped(json, false);
}

export function HourlyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hourly {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
        'temp': json['temp'],
        'humidity': json['humidity'],
        'wind': json['wind'],
        'precipitation': json['precipitation'],
    };
}

export function HourlyToJSON(value?: Hourly | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'time': value['time'],
        'temp': value['temp'],
        'humidity': value['humidity'],
        'wind': value['wind'],
        'precipitation': value['precipitation'],
    };
}

