/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Hourly } from './Hourly';
import {
    HourlyFromJSON,
    HourlyFromJSONTyped,
    HourlyToJSON,
} from './Hourly';

/**
 * 
 * @export
 * @interface Weather
 */
export interface Weather {
    /**
     * 
     * @type {number}
     * @memberof Weather
     */
    elevation: number;
    /**
     * 
     * @type {Array<Hourly>}
     * @memberof Weather
     */
    hourly: Array<Hourly>;
}

/**
 * Check if a given object implements the Weather interface.
 */
export function instanceOfWeather(value: object): value is Weather {
    if (!('elevation' in value) || value['elevation'] === undefined) return false;
    if (!('hourly' in value) || value['hourly'] === undefined) return false;
    return true;
}

export function WeatherFromJSON(json: any): Weather {
    return WeatherFromJSONTyped(json, false);
}

export function WeatherFromJSONTyped(json: any, ignoreDiscriminator: boolean): Weather {
    if (json == null) {
        return json;
    }
    return {
        
        'elevation': json['elevation'],
        'hourly': ((json['hourly'] as Array<any>).map(HourlyFromJSON)),
    };
}

export function WeatherToJSON(value?: Weather | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'elevation': value['elevation'],
        'hourly': ((value['hourly'] as Array<any>).map(HourlyToJSON)),
    };
}

