/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUserResponse
 */
export interface LoginUserResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginUserResponse
     */
    token: string;
}

/**
 * Check if a given object implements the LoginUserResponse interface.
 */
export function instanceOfLoginUserResponse(value: object): value is LoginUserResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginUserResponseFromJSON(json: any): LoginUserResponse {
    return LoginUserResponseFromJSONTyped(json, false);
}

export function LoginUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LoginUserResponseToJSON(value?: LoginUserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

