server.port=8081
spring.application.name=apis
geo.open.meteo.base.url=https://geocoding-api.open-meteo.com
forecast.open.meteo.base.url=https://api.open-meteo.com
serp.api.base.url=https://serpapi.com
serp.api.key=4abad2ada72caa496f35fd3972a8724210feb6bc391d0c39e643cae40d4c4700
jwt.secret.key=my_super_secret_key_25625273ldsfjhgdfs74rbkjhgdfsaouygq34rt987ljhbasdkjfhg08yqejrb.1231
open.plz.api.base.url=https://openplzapi.org

