/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Events,
} from '../models/index';
import {
    EventsFromJSON,
    EventsToJSON,
} from '../models/index';

export interface EventsGETRequest {
    location: string;
}

/**
 * EventsApiControllerApi - interface
 * 
 * @export
 * @interface EventsApiControllerApiInterface
 */
export interface EventsApiControllerApiInterface {
    /**
     * 
     * @summary Some summary
     * @param {string} location 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiControllerApiInterface
     */
    eventsGETRaw(requestParameters: EventsGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Events>>;

    /**
     * Some summary
     */
    eventsGET(requestParameters: EventsGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Events>;

}

/**
 * 
 */
export class EventsApiControllerApi extends runtime.BaseAPI implements EventsApiControllerApiInterface {

    /**
     * Some summary
     */
    async eventsGETRaw(requestParameters: EventsGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Events>> {
        if (requestParameters['location'] == null) {
            throw new runtime.RequiredError(
                'location',
                'Required parameter "location" was null or undefined when calling eventsGET().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/{location}`.replace(`{${"location"}}`, encodeURIComponent(String(requestParameters['location']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventsFromJSON(jsonValue));
    }

    /**
     * Some summary
     */
    async eventsGET(requestParameters: EventsGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Events> {
        const response = await this.eventsGETRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
