/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Locations,
} from '../models/index';
import {
    LocationsFromJSON,
    LocationsToJSON,
} from '../models/index';

export interface LocationGETRequest {
    postalCode?: string;
    city?: string;
}

/**
 * LocationApiControllerApi - interface
 * 
 * @export
 * @interface LocationApiControllerApiInterface
 */
export interface LocationApiControllerApiInterface {
    /**
     * At least one of the following query parameters must be provided: **postalCode** or **city**. 
     * @summary Some summary
     * @param {string} [postalCode] 
     * @param {string} [city] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationApiControllerApiInterface
     */
    locationGETRaw(requestParameters: LocationGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Locations>>;

    /**
     * At least one of the following query parameters must be provided: **postalCode** or **city**. 
     * Some summary
     */
    locationGET(requestParameters: LocationGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Locations>;

}

/**
 * 
 */
export class LocationApiControllerApi extends runtime.BaseAPI implements LocationApiControllerApiInterface {

    /**
     * At least one of the following query parameters must be provided: **postalCode** or **city**. 
     * Some summary
     */
    async locationGETRaw(requestParameters: LocationGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Locations>> {
        const queryParameters: any = {};

        if (requestParameters['postalCode'] != null) {
            queryParameters['postalCode'] = requestParameters['postalCode'];
        }

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/location`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationsFromJSON(jsonValue));
    }

    /**
     * At least one of the following query parameters must be provided: **postalCode** or **city**. 
     * Some summary
     */
    async locationGET(requestParameters: LocationGETRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Locations> {
        const response = await this.locationGETRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
