/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Weather,
} from '../models/index';
import {
    WeatherFromJSON,
    WeatherToJSON,
} from '../models/index';

export interface WeatherGETRequest {
    cityName: string;
}

/**
 * WeatherApiControllerApi - interface
 * 
 * @export
 * @interface WeatherApiControllerApiInterface
 */
export interface WeatherApiControllerApiInterface {
    /**
     * 
     * @summary Some summary
     * @param {string} cityName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherApiControllerApiInterface
     */
    weatherGETRaw(requestParameters: WeatherGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Weather>>;

    /**
     * Some summary
     */
    weatherGET(requestParameters: WeatherGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Weather>;

}

/**
 * 
 */
export class WeatherApiControllerApi extends runtime.BaseAPI implements WeatherApiControllerApiInterface {

    /**
     * Some summary
     */
    async weatherGETRaw(requestParameters: WeatherGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Weather>> {
        if (requestParameters['cityName'] == null) {
            throw new runtime.RequiredError(
                'cityName',
                'Required parameter "cityName" was null or undefined when calling weatherGET().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/weather/{cityName}`.replace(`{${"cityName"}}`, encodeURIComponent(String(requestParameters['cityName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeatherFromJSON(jsonValue));
    }

    /**
     * Some summary
     */
    async weatherGET(requestParameters: WeatherGETRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Weather> {
        const response = await this.weatherGETRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
